# Evaluation configuration for Goodreads

# Evaluation directory where auxiliary eval files are stored.
eval_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/data/eval"

# Category (subfolder within eval_dir).
category: "Goodreads"

# Prediction results file (input)
base_predictions_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/predictions/"
predictions_filename: "raw_results_1000.json"
predictions_file: ""


# predictions_file: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/predictions/DS-DPO/Div_10_1.0/dpc_0.08_3.0/raw_results_1000.json"
# predictions_file: "/scratch/user/chuanhsin0110/test_0321/nlp/predictions/raw_results_1000.json"

# Output file for evaluation results (JSON)
# tuned_model: "sigmoid_DS-DPO"
tuned_model: "S-DPO"
method: "Div_5_1.0"
base_output_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/metrics/"
output_filename: "eval_result.json"
distance_type: "dpc"
min_beta: 0.01
max_beta: 0.15
beta: 0.11
num_train_epochs: 1
output_file: ""


# output_file: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/metrics/predictions/DS-DPO/Div_10_1.0/dpc_0.08_3.0/eval_result.json"
# output_file: "/scratch/user/chuanhsin0110/test_0321/nlp/metrics/eval_result.json"

# Optional CSV file to update evaluation metrics.
exp_csv: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/metrics/metrics_summary.csv"
# exp_csv: "/scratch/user/chuanhsin0110/test_0321/nlp/metrics/metrics_summary.csv"

# Evaluation parameter: top-k for ranking metrics.
topk: 10

# Model name and sampling method (for record purposes)
model_name: ""
sample_method: ""
temperature: 1.0

# model_name: "DS-DPO"
# sample_method: "dpc_0.08_3.0"

# SentenceTransformer model path for encoding predictions.
sbert_model_path: "./models/paraphrase-MiniLM-L3-v2"
