# config/lightgcn_config.yaml
# Configuration for LightGCN training on Goodreads dataset

# Root directory for data and model outputs
data_dir: /scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/lightgcn

# Paths to interaction JSON files
train_json: /scratch/user/chuanhsin0110/ClusterExposure-DPO/data/raw/Goodreads/train.json
valid_json: /scratch/user/chuanhsin0110/ClusterExposure-DPO/data/raw/Goodreads/valid.json

# Model checkpoint filename (saved under data_dir/models)
model_filename: lightgcn_model_full_data.pth

# Model architecture parameters
embedding_dim: 64   # embedding dimension for users and items
num_layers: 3       # number of LightGCN propagation layers

# Training hyperparameters
learning_rate: 1e-3 # Adam optimizer learning rate
epochs: 5           # number of training epochs
batch_size: 1024    # batch size for BPR sampling

# Random seed for reproducibility
seed: 0
