# config/lightgcn_neg_sampling.yaml

# 输入的候选集目录（不包含具体文件名），内部会拼 param_tag
input_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/data/beam_cd_candidates"

# 与 param_tag 一致，用于定位子文件夹 beam_cd_candidates/{param_tag}
# 这里 D 就是 “Div” ，如果你的文件夹命名是 Div_10_1.0 就写成 "Div"
D: "Div"
num_return_sequences: 10
diversity_penalty: 1.0

# annotated 训练/验证 文件名
input_train_filename: "annotated_train.json"
input_valid_filename: "annotated_valid.json"

# 输出负样本的根目录，最终结果会写到
# output_dir_base/{param_tag}/{策略}/{split}.json
output_dir_base: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/data/lightgcn"

# CF embedding 相关
# book2idx 映射文件（JSON）
book2idx: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/lightgcn/models/book2idx_full_data_with_output.json"
# 预先导出的 item_embeddings (NumPy .npy)
item_emb: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/lightgcn/models/lightgcn_model_full_data_with_output.npy"
