# Model settings
base_model: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
finetuned_path: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/SPRec_model/final_model"

# Data settings
test_data_path: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/data/sampled/Goodreads/test.json"

# Output settings
output_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/predictions/SPRec_Reproduction"

# Inference parameters
batch_size: 8
max_new_tokens: 50
test_sample_size: 1000
