# Model settings
base_model: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
base_finetuned_path: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/"
finetuned_path: ""
# finetuned_path: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/model/DS-DPO/Div_10_1.0/dpc_0.1_4.0"
# finetuned_path: "/scratch/user/chuanhsin0110/test_0321/nlp/models/final/final_model"

# Data settings
test_data_path: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/data/sampled/Goodreads/test.json"

# Output settings
tuned_model: "DS-DPO"
# method: "Div_5_1.0"
method: "Div_5_1.0"
distance_type: "dpc"
min_beta: 0.08
max_beta: 1.02
num_train_epochs: 1
base_output_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/predictions/"
output_dir: ""


# output_dir: "/scratch/user/chuanhsin0110/ClusterExposure-DPO/experiments/predictions/DS-DPO/Div_10_1.0/dpc_0.1_4.0"
# output_dir: "/scratch/user/chuanhsin0110/test_0321/nlp/predictions"
# Inference parameters
batch_size: 8
max_new_tokens: 50
test_sample_size: 1000
